[workspace]
resolver = "2"
members = [
    "core",
    "utils",
    "utils/alloc",
    "math",
    "crypto/hashes",
    "crypto/txscript/errors",
    "crypto/txscript",
    "crypto/addresses",
    "crypto/merkle",
    "crypto/muhash",
    "consensus/core",
    "consensus",
    "database",
    "components/addressmanager",
    "components/connectionmanager",
    "components/consensusmanager",
    "protocol/p2p",
    "protocol/flows",
    "consensus/pow",
    "mining/errors",
    "mining",
    "indexes/core",
    "indexes/processor",
    "indexes/utxoindex",
    "notify",
    "metrics/core",
    "metrics/perf_monitor",
    "rpc/core",
    "rpc/service",
    "rpc/macros",
    "rpc/grpc/core",
    "rpc/grpc/server",
    "rpc/grpc/client",
    "rpc/wrpc/server",
    "rpc/wrpc/client",
    "rpc/wrpc/proxy",
    "rpc/wrpc/wasm",
    "daemon",
    "jiopad",
    "wallet/bip32",
    "wallet/keys",
    "wallet/core",
    "wallet/wasm",
    "wasm",
    "cli",
    "testing/integration",
    "simpa",
    "rothschild",
]

[workspace.package]
version = "0.1.0"
authors = ["jio developers"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.74"
repository = "https://github.com/x-93/rusty-jio"

[workspace.dependencies]
# Workspace crates
jio-core = { version = "0.1.0", path = "core" }
jio-utils = { version = "0.1.0", path = "utils" }
jio-alloc = { version = "0.1.0", path = "utils/alloc" }
jio-math = { version = "0.1.0", path = "math" }
jio-hashes = { version = "0.1.0", path = "crypto/hashes" }
jio-merkle = { version = "0.1.0", path = "crypto/merkle" }
jio-muhash = { version = "0.1.0", path = "crypto/muhash" }
jio-txscript-errors = { version = "0.1.0", path = "crypto/txscript/errors" }
jio-txscript = { version = "0.1.0", path = "crypto/txscript" }
jio-addresses = { version = "0.1.0", path = "crypto/addresses" }
jio-consensus-core = { version = "0.1.0", path = "consensus/core" }
jio-consensus = { version = "0.1.0", path = "consensus" }
jio-consensus-pow = { version = "0.1.0", path = "consensus/pow" }
jio-database = { version = "0.1.0", path = "database" }
jio-addressmanager = { version = "0.1.0", path = "components/addressmanager" }
jio-connectionmanager = { version = "0.1.0", path = "components/connectionmanager" }
jio-consensusmanager = { version = "0.1.0", path = "components/consensusmanager" }
jio-p2p = { version = "0.1.0", path = "protocol/p2p" }
jio-protocol-flows = { version = "0.1.0", path = "protocol/flows" }
jio-mining-errors = { version = "0.1.0", path = "mining/errors" }
jio-mining = { version = "0.1.0", path = "mining" }
jio-indexes-core = { version = "0.1.0", path = "indexes/core" }
jio-indexes-processor = { version = "0.1.0", path = "indexes/processor" }
jio-utxoindex = { version = "0.1.0", path = "indexes/utxoindex" }
jio-notify = { version = "0.1.0", path = "notify" }
jio-metrics-core = { version = "0.1.0", path = "metrics/core" }
jio-perf-monitor = { version = "0.1.0", path = "metrics/perf_monitor" }
jio-rpc-core = { version = "0.1.0", path = "rpc/core" }
jio-rpc-service = { version = "0.1.0", path = "rpc/service" }
jio-rpc-macros = { version = "0.1.0", path = "rpc/macros" }
jio-grpc-core = { version = "0.1.0", path = "rpc/grpc/core" }
jio-grpc-server = { version = "0.1.0", path = "rpc/grpc/server" }
jio-grpc-client = { version = "0.1.0", path = "rpc/grpc/client" }
jio-wrpc-server = { version = "0.1.0", path = "rpc/wrpc/server" }
jio-wrpc-client = { version = "0.1.0", path = "rpc/wrpc/client" }
jio-wrpc-proxy = { version = "0.1.0", path = "rpc/wrpc/proxy" }
jio-wrpc-wasm = { version = "0.1.0", path = "rpc/wrpc/wasm" }
jio-daemon = { version = "0.1.0", path = "daemon" }
jiopad = { version = "0.1.0", path = "jiopad" }
jio-bip32 = { version = "0.1.0", path = "wallet/bip32" }
jio-wallet-keys = { version = "0.1.0", path = "wallet/keys" }
jio-wallet-core = { version = "0.1.0", path = "wallet/core" }
jio-wallet-wasm = { version = "0.1.0", path = "wallet/wasm" }
jio-wasm = { version = "0.1.0", path = "wasm" }
jio-cli = { version = "0.1.0", path = "cli" }
jio-testing-integration = { version = "0.1.0", path = "testing/integration" }
jio-simpa = { version = "0.1.0", path = "simpa" }
jio-rothschild = { version = "0.1.0", path = "rothschild" }

# External crates
thiserror = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12"
async-trait = "0.1"
blake2b_simd = "1.0"
blake3 = "1.5"
sha2 = "0.10"
ripemd = "0.1"
subtle = "2.5"
hex = "0.4"
borsh = { version = "1.5", features = ["derive"] }
faster-hex = "0.9"
smallvec = "1.13"
cfg-if = "1.0"
enum-primitive-derive = "0.3"
num-traits = "0.2"
hmac = "0.12"
secp256k1 = { version = "0.29", features = ["global-context", "rand-std", "serde"] }
bip39 = { version = "2.0", features = ["rand"] }
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
