[package]
name = "jio-txscript"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
jio-hashes = { workspace = true }
jio-addresses = { workspace = true }
jio-txscript-errors = { path = "errors" }
secp256k1 = { workspace = true }
borsh = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ["borsh", "serde"]
borsh = ["dep:borsh", "jio-txscript-errors/borsh"]
serde = ["dep:serde", "jio-txscript-errors/serde"]
