[package]
name = "jio-hashes"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-utils = { workspace = true }
jio-math = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
ripemd = { workspace = true }
blake2b_simd = { workspace = true }
blake3 = { workspace = true }
subtle = { workspace = true }
borsh = { workspace = true }
faster-hex = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[[bench]]
name = "bench"
harness = false

