[package]
name = "jio-math"
description = "Jio math primitives"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
borsh = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
js-sys = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench"
harness = false

[features]
default = ["borsh", "serde"]
borsh = ["dep:borsh", "borsh/std"]
serde = ["dep:serde"]
wasm = ["dep:wasm-bindgen", "dep:js-sys"]