[package]
name = "jio-math"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-utils = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
subtle = { workspace = true }
faster-hex = { workspace = true }
borsh = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
