[package]
name = "jio-txscript-errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
borsh = { workspace = true, optional = true }

[features]
default = ["serde", "borsh"]
serde = ["dep:serde"]
borsh = ["dep:borsh"]
