[package]
name = "jio-core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-utils = { workspace = true }
jio-hashes = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }
cfg-if = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
