use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum JioPayloadType {
    Addresses,
    Block,
    BlockHeader,
    BlockLocator,
    DoneBlocks,
    DoneHeaders,
    IbdBlock,
    IbdBlockLocator,
    InvRelayBlock,
    InvTransactions,
    Ping,
    Pong,
    PruningPointUtxoSetChunk,
    PruningPoints,
    Reject,
    RequestAddresses,
    RequestAntipast,
    RequestBlockLocator,
    RequestBlocks,
    RequestHeaders,
    RequestIbdBlocks,
    RequestIbdChainBlockLocator,
    RequestNextHeaders,
    RequestNextPruningPointUtxoSetChunk,
    RequestPruningPointAndAnticone,
    RequestPruningPointProof,
    RequestPruningPointUtxoSet,
    RequestRelayBlocks,
    RequestTransactions,
    Transaction,
    TransactionNotFound,
    TrustedData,
    Verack,
    Version,
}
