[package]
name = "jio-wasm"
description = "JIO bindings"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
# wasm-pack requires this value to be a string
# (it can not be derived from the workspace)
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
jio-core.workspace = true
jio-wallet-core.workspace = true
wasm-bindgen.workspace = true
jio-addresses.workspace = true
jio-utils.workspace = true
jio-rpc-core.workspace = true
jio-wrpc-client.workspace = true

[features] 
wallet = [] 
full = ["wallet"] 
default = [] 
