[package]
name = "jio-wasm"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-consensus-core = { workspace = true }
jio-consensus-pow = { workspace = true }
jio-wallet-core = { workspace = true }
jio-addresses = { workspace = true }
jio-txscript = { workspace = true }
serde = { workspace = true }
