[package]
name = "jio-metrics-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
borsh = { workspace = true, optional = true }

[features]
default = ["serde", "borsh"]
serde = ["dep:serde"]
borsh = ["dep:borsh"]
