[package]
name = "jio-p2p"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-core = { workspace = true }
jio-utils = { workspace = true }
jio-hashes = { workspace = true }
jio-consensus-core = { workspace = true }
jio-addressmanager = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
smallvec = { workspace = true }
bytes = "1.6"
serde_json = { workspace = true }
