[package]
name = "jio-consensus-pow"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-hashes = { path = "../../crypto/hashes" }
jio-consensus-core = { path = "../core" }
jio-math = { path = "../../math" }
blake3 = "1.8"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
smallvec = "1.13"
