[package]
name = "jio-protocol-flows"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-p2p = { workspace = true }
jio-consensus = { workspace = true }
jio-consensus-core = { workspace = true }
jio-consensusmanager = { workspace = true }
jio-addressmanager = { workspace = true }
jio-connectionmanager = { workspace = true }
jio-core = { workspace = true }
jio-utils = { workspace = true }
jio-hashes = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
