[package]
name = "jio-utils"
description = "Jio utility functions"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
faster-hex = { workspace = true, features = ["alloc"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["std", "serde"]
std = ["faster-hex/std"]
serde = ["dep:serde", "dep:serde_json"]
