[package]
name = "jio-consensus"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-consensus-core = { workspace = true }
jio-database = { workspace = true }
jio-hashes = { workspace = true }
jio-txscript = { workspace = true }
jio-addresses = { workspace = true }
jio-math = { workspace = true }
jio-utils = { workspace = true }
jio-core = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
subtle = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
