[package]
name = "jio-mining"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
jio-addresses.workspace = true
jio-hashes.workspace = true
jio-muhash.workspace = true
jio-consensus-core.workspace = true
jio-txscript.workspace = true
jio-core.workspace = true
thiserror.workspace = true
serde.workspace = true
log.workspace = true
futures-util.workspace = true
smallvec.workspace = true
rand.workspace = true
parking_lot.workspace = true

[dev-dependencies]
jio-txscript.workspace = true
criterion.workspace = true
secp256k1 = { version = "0.24", features = ["global-context", "rand-std"] }

[[bench]]
name = "bench"
harness = false
