[package]
name = "jio-utxoindex"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jio-indexes-core = { workspace = true }
jio-consensus-core = { workspace = true }
jio-consensus = { workspace = true }
jio-consensusmanager = { workspace = true }
jio-database = { workspace = true }
jio-core = { workspace = true }
jio-hashes = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
smallvec = { workspace = true }
